plugin_roots:
  - /path/to/a
  - /path/to/b
plugin_order:
  DataModel:
    - Name of Plugin A
    - Name of Plugin B
  Extraction:
    - Name of Plugin D. Plugins E and F are omitted and will be ordered naturally following Plugin D
  PostProcessing: # An empty array or non-existent key indicates all plugins will be ordered naturally
  Validation:
  Storage:
plugin_config:
  DataModel:
    Name of Plugin A: # This illustrates usage of keyword args with plugins
      name_of__init__paramter: value to pass
      name_of_another__init__paramter: 1
      name_of_yet_another__init__paramter: True
      name_of_one_final__init__paramter:
        - 1
        - 2
        - 3
    Name of Plugin B: # This illustrates usage of standard args with plugins
      - first param
      - second param
      - 3
      - fouth param
      - true
    Name of Plugin C: something # This is not a list/mapping and hence will be ignored
plugins: # This section can be omitted entirely if you wish to simply use all available plugins
  mode: blacklist # Valid options are whitelist and blacklist. Defaults to blacklist if not specified
  DataModel:
    - Name of Plugin A
    - Name of Plugin B
